# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  # pre-commit.ci does not support networking which is required to install pyright, so we run it separately in CI:
  # https://github.com/pre-commit-ci/issues/issues/55#issuecomment-822481997
  skip: [pyright]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.4
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
      - id: pyright
        additional_dependencies:
          - "pyright[nodejs]"
          # [[[cog
          # import subprocess
          # for package in subprocess.check_output(
          #     ["uv", "export", "--quiet", "--no-hashes", "--no-header", "--no-annotate", "--format", "requirements-txt"],
          #     text=True
          # ).splitlines():
          #     print(f'- "{package}"')
          # ]]]
          - "appium-python-client==4.5.1"
          - "arrow==1.3.0"
          - "attrs==25.1.0"
          - "certifi==2025.1.31"
          - "cffi==1.17.1 ; implementation_name != 'pypy' and os_name == 'nt'"
          - "cfgv==3.4.0"
          - "click==8.1.8"
          - "colorama==0.4.6 ; sys_platform == 'win32'"
          - "distlib==0.3.9"
          - "filelock==3.17.0"
          - "h11==0.14.0"
          - "identify==2.6.8"
          - "idna==3.10"
          - "iniconfig==2.0.0"
          - "markdown-it-py==3.0.0"
          - "mdurl==0.1.2"
          - "nodeenv==1.9.1"
          - "outcome==1.3.0.post0"
          - "packaging==24.2"
          - "platformdirs==4.3.6"
          - "pluggy==1.5.0"
          - "pre-commit==4.1.0"
          - "pycparser==2.22 ; implementation_name != 'pypy' and os_name == 'nt'"
          - "pygments==2.19.1"
          - "pysocks==1.7.1"
          - "pytest==8.3.5"
          - "python-dateutil==2.9.0.post0"
          - "pyyaml==6.0.2"
          - "rich==13.9.4"
          - "selenium==4.29.0"
          - "shellingham==1.5.4"
          - "six==1.17.0"
          - "sniffio==1.3.1"
          - "sortedcontainers==2.4.0"
          - "trio==0.29.0"
          - "trio-websocket==0.12.2"
          - "typer==0.15.2"
          - "types-python-dateutil==2.9.0.20241206"
          - "typing-extensions==4.12.2"
          - "urllib3==2.3.0"
          - "virtualenv==20.29.3"
          - "websocket-client==1.8.0"
          - "wsproto==1.2.0"
          # [[[end]]]
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-footnote
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-tables
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: local
    hooks:
      - name: cog
        id: cog
        entry: cog
        args: [-P, --check, -r, "@cogs.txt"]
        language: python
        always_run: true
        pass_filenames: false
        additional_dependencies:
          - cogapp
          - uv
