name: Main CI
on:
  push:
    branches:
      - main
jobs:
  prci:
    uses: ./.github/workflows/prci.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: prci
    permissions:
      contents: write
      pull-requests: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
